# Generated by Django 5.2.17 on 2026-09-11 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=32)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=100)),
                ('setup_type', models.CharField(blank=True, max_length=255)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='research_an_user_id_ffa9cb_idx'), models.Index(fields=['ticker', 'created_at'], name='research_an_ticker_2e1ac6_idx')],
            },
        ),
    ]
