# Generated by Django 5.2.17 on 2026-09-11 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('analysis', 'Analysis'), ('scan', 'Scan'), ('other', 'Other')], max_length=20)),
                ('ticker', models.CharField(blank=True, max_length=32)),
                ('units', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='usage_usage_user_id_e1172f_idx'), models.Index(fields=['event_type', 'created_at'], name='usage_usage_event_t_2ce4fb_idx')],
            },
        ),
    ]
